name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      run: gcloud auth application-default login

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        tf_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

      